operator: fix bug in api conversion
The bug manifested as:
```
  File "/src/l7mp.py", line 313, in convert_sub

    obj[schema['x-l7mp-old-property']] = subkey

  TypeError: 'str' object does not support item assignment
```